### ISSUE TITLE
[ERROR] Too many values to unpack

### ISSUE THREAD

**Issue by 0rangeAppl3** [Kav-K/GPTDiscord#274]
**Describe the bug**
/internet chat returns error: too many value to unpack (expected 3)
![image](https://user-images.githubusercontent.com/14069364/233104648-325bfc2a-21ff-422d-8697-ea504694527a.png)

**To Reproduce**
1. /internet chat
2. search_scopes: set bigger than 3. there is higher chance this issue happen with scope 6 or 5.
3. it happens randomly

**Console log return**
WARNING:langchain.chat_models.openai:Retrying langchain.chat_models.openai.ChatOpenAI.completion_with_retry.<locals>._completion_with_retry in 16.0 seconds as it raised RateLimitError: Rate limit reached for default-gpt-3.5-turbo in organization org-XKJtTnIVndqMLhKmdkk5UFsb on requests per min. Limit: 3 / min. Please try again in 20s. Contact support@openai.com if you continue to have issues. Please add a payment method to your account to increase your rate limit. Visit https://platform.openai.com/account/billing to add a payment method..
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\GPT3Discord\cogs\search_service_cog.py", line 182, in on_message
    response = await self.bot.loop.run_in_executor(None, agent.run, prompt)
  File "C:\python\python39\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\python\python39\lib\site-packages\langchain\chains\base.py", line 213, in run
    return self(args[0])[self.output_keys[0]]
  File "C:\python\python39\lib\site-packages\langchain\chains\base.py", line 116, in __call__
    raise e
  File "C:\python\python39\lib\site-packages\langchain\chains\base.py", line 113, in __call__
    outputs = self._call(inputs)
  File "C:\python\python39\lib\site-packages\langchain\agents\agent.py", line 792, in _call
    next_step_output = self._take_next_step(
  File "C:\python\python39\lib\site-packages\langchain\agents\agent.py", line 672, in _take_next_step
    output = self.agent.plan(intermediate_steps, **inputs)
  File "C:\python\python39\lib\site-packages\langchain\agents\agent.py", line 385, in plan
    return self.output_parser.parse(full_output)
  File "C:\python\python39\lib\site-packages\langchain\agents\conversational_chat\output_parser.py", line 20, in parse
    cleaned_output, _ = cleaned_output.split("```")
ValueError: too many values to unpack (expected 2)

**Comment by Raecaug** [comment]
@Kav-K Found this issue on the main langchain repo. Perhaps this is the source?:

https://github.com/hwchase17/langchain/issues/2679#issue-1661258754

**Comment by Kav-K** [comment]
So an update on this, this seems to be an issue with langchain, can be seen in the link above provided by @Raecaug. This issue happens when the chat agent is asked to generate code. Langchain's output parser incorrectly handles the triple backticks in agent output that contains code. To avoid this issue, don't use the internet chat feature on the bot to do programming (you shouldn't be doing this anyways, it's not what it's meant for), or manually ask the agent in the prompt to avoid using backticks.
I'll try to push for this issue to be resolved but I would love everyone's help, please comment at https://github.com/hwchase17/langchain/issues/2679#issue-1661258754 if this issue affects you

**Comment by Kav-K** [comment]
I put on a temp fix for this but this needs to be addressed by langchain..
