### ISSUE TITLE
[BUG] Error while resetting index

### ISSUE THREAD

**Issue by fmunim** [Kav-K/GPTDiscord#287]
**Describe the bug**
Getting this while resetting the index:
```
Ignoring exception in on_application_command_error
Traceback (most recent call last):
  File "/home/xxx/.local/lib/python3.9/site-packages/discord/commands/core.py", line 124, in wrapped
    ret = await coro(arg)
  File "/home/xxx/.local/lib/python3.9/site-packages/discord/commands/core.py", line 978, in _invoke
    await self.callback(self.cog, ctx, **kwargs)
  File "/home/xxx/xxx/cogs/commands.py", line 182, in delete_all_conversation_threads
    await self.converser_cog.delete_all_conversation_threads_command(ctx)
  File "/home/xxx/gpt2/cogs/text_service_cog.py", line 855, in delete_all_conversation_threads_command
    await ctx.respond("All conversation threads in this server have been deleted.")
  File "/home/xxx/.local/lib/python3.9/site-packages/discord/commands/context.py", line 286, in respond
    return await self.followup.send(*args, **kwargs)  # self.send_followup
  File "/home/xxx/.local/lib/python3.9/site-packages/discord/webhook/async_.py", line 1745, in send
    data = await adapter.execute_webhook(
  File "/home/xxx/.local/lib/python3.9/site-packages/discord/webhook/async_.py", line 219, in request
    raise NotFound(response, data)
discord.errors.NotFound: 404 Not Found (error code: 10008): Unknown Message

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/xxx/.local/lib/python3.9/site-packages/discord/client.py", line 378, in _run_event
    await coro(*args, **kwargs)
  File "/home/xxx/xxx/gpt3discord.py", line 120, in on_application_command_error
    raise error
  File "/home/xxx/.local/lib/python3.9/site-packages/discord/bot.py", line 1114, in invoke_application_command
    await ctx.command.invoke(ctx)
  File "/home/xxx/.local/lib/python3.9/site-packages/discord/commands/core.py", line 375, in invoke
    await injected(ctx)
  File "/home/xxx/.local/lib/python3.9/site-packages/discord/commands/core.py", line 124, in wrapped
    ret = await coro(arg)
  File "/home/xxx/.local/lib/python3.9/site-packages/discord/commands/core.py", line 1312, in _invoke
    await command.invoke(ctx)
  File "/home/xxx/.local/lib/python3.9/site-packages/discord/commands/core.py", line 375, in invoke
    await injected(ctx)
  File "/home/xxx/.local/lib/python3.9/site-packages/discord/commands/core.py", line 132, in wrapped
    raise ApplicationCommandInvokeError(exc) from exc
discord.errors.ApplicationCommandInvokeError: Application Command raised an exception: NotFound: 404 Not Found (error code: 10008): Unknown Message
Traceback (most recent call last):
  File "/home/xxx/xxx/models/index_model.py", line 177, in reset_indexes
    EnvService.find_shared_file(f"indexes/{user_id}_search")
  File "/home/xxx/xxx/services/environment_service.py", line 73, in find_shared_file
    raise ValueError(f"Unable to find shared data file {file_name}")
ValueError: Unable to find shared data file indexes/417185533564026882_search
```

**To Reproduce**
- Add a index
- Try resetting

**Expected behavior**
Reset to be successful, but seems not

**Screenshots**
N/A

**Additional context**
N/A

**Comment by Kav-K** [comment]
Fixed
