### ISSUE TITLE
[INDEX TALK ISSUE] fail to parsed text and the chat keep hanging

### ISSUE THREAD

**Issue by 0rangeAppl3** [Kav-K/GPTDiscord#291]
**Describe the bug**
Index talk works great for the first 3 4 request. then it get stucks after request 4,5. Console show completion text but it fail to parsed to chat window. And there is no way to reset the chat. Have to delete the thread and start a new one.

**Additional context**
`
> Entering new AgentExecutor chain...
Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\python\python39\lib\site-packages\discord\client.py", line 377, in _run_event
    await coro(*args, **kwargs)
  File "D:\GPTDiscord\cogs\index_service_cog.py", line 80, in on_message
    chat_result = await self.index_handler.execute_index_chat_message(
  File "D:\GPTDiscord\models\index_model.py", line 239, in execute_index_chat_message
    agent_output = await self.loop.run_in_executor(
  File "C:\python\python39\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\python\python39\lib\site-packages\langchain\chains\base.py", line 213, in run
    return self(args[0])[self.output_keys[0]]
  File "C:\python\python39\lib\site-packages\langchain\chains\base.py", line 116, in __call__
    raise e
  File "C:\python\python39\lib\site-packages\langchain\chains\base.py", line 113, in __call__
    outputs = self._call(inputs)
  File "C:\python\python39\lib\site-packages\langchain\agents\agent.py", line 792, in _call
    next_step_output = self._take_next_step(
  File "C:\python\python39\lib\site-packages\langchain\agents\agent.py", line 672, in _take_next_step
    output = self.agent.plan(intermediate_steps, **inputs)
  File "C:\python\python39\lib\site-packages\langchain\agents\agent.py", line 385, in plan
    return self.output_parser.parse(full_output)
  File "C:\python\python39\lib\site-packages\langchain\agents\conversational\output_parser.py", line 19, in parse
    raise ValueError(f"Could not parse LLM output: `{text}`")
ValueError: Could not parse LLM output: `Thought: Do I need to use a tool? No

Yes, a candidate in Hanoi can apply for this job. The job description does not specify any location requirements, so as long as the candidate meets the other requirements and is able to work remotely or relocate if necessary, they should be able to apply for the position. However, it is always a good idea to check with the company directly to confirm their policies on remote work and location requirements.```

**Screenshot**
![image](https://user-images.githubusercontent.com/14069364/234821322-2a2ca8fe-2f43-4ccb-bf34-2e7a0ae46a17.png)
![image](https://user-images.githubusercontent.com/14069364/234821466-3b7b4575-99f8-43fb-acac-f2db91670e76.png)

**Comment by Kav-K** [comment]
A lot of issues with index talk should be fixed now, open a new issue if you are still running into problems
