### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by AreYouMehmetEfeisModder** [Kav-K/GPTDiscord#324]
Traceback (most recent call last):
  File "C:\Users\MehmetEfeFriday\Desktop\Projects\Proiect4 maybe\GPTDiscord-main\GPTDiscord-main\gpt3discord.py", line 22, in <module>
    from cogs.index_service_cog import IndexService
  File "C:\Users\MehmetEfeFriday\Desktop\Projects\Proiect4 maybe\GPTDiscord-main\GPTDiscord-main\cogs\index_service_cog.py", line 13, in <module>
    from models.index_model import Index_handler
  File "C:\Users\MehmetEfeFriday\Desktop\Projects\Proiect4 maybe\GPTDiscord-main\GPTDiscord-main\models\index_model.py", line 66, in <module>
    EpubReader = download_loader("EpubReader")
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MehmetEfeFriday\AppData\Local\Programs\Python\Python311\Lib\site-packages\llama_index\readers\download.py", line 133, in download_loader
    library = json.loads(library_raw_content)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MehmetEfeFriday\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MehmetEfeFriday\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 4 (char 3)

**Comment by Matthew-Dreemurr** [comment]
Same for me with docker :/

Here my config used and logs
https://gist.github.com/Matthew-Dreemurr/05353525efbd9d8aea71707378b265d0

**Comment by JoNilsson** [comment]
> Same for me with docker :/
> 
> Here my config used and logs https://gist.github.com/Matthew-Dreemurr/05353525efbd9d8aea71707378b265d0

https://gist.github.com/Matthew-Dreemurr/05353525efbd9d8aea71707378b265d0?permalink_comment_id=4591691#gistcomment-4591691

@Kav-K 

We're seeing a pattern here.  Any ideas why this seems to be externally b0rk3d?

**Comment by JoNilsson** [comment]
As a temporary work around for whatever the underlying issue might be
Commenting out the IndexService from line 22 above as well as it's referenced use, will get you back up and running.

Caveat Emptor; You won't have any of the index features, nor Internet Chat. But you can still have conversations and other features.

I may have more time to look into what the actual issue is in the next few days if Kav hasn't gotten back to us.

**Comment by XuT** [comment]
https://github.com/Kav-K/GPTDiscord/compare/main...lsnk:GPTDiscord:main this fork is worked but not for dockers.

**Comment by JoNilsson** [comment]
@XuT No.  It runs in containerization just fine, so long as external deps don't break it. 
_As is the suspected case here._

**Comment by deadbits** [comment]
I'm getting the same error, as well. Exception raised on first run.

```
 $ gpt3discord                                                
Loading environment from .env
Loading environment from /home/adam/Research/machine-learning/GPTDiscord/GPTDiscord/etc/environment
Loading environment from None
Attempting to retrieve the settings DB
Retrieved the settings DB
Downloading (…)olve/main/vocab.json: 100%|█████████████████████████████████| 1.04M/1.04M [00:00<00:00, 15.8MB/s]
Downloading (…)olve/main/merges.txt: 100%|███████████████████████████████████| 456k/456k [00:00<00:00, 30.9MB/s]
Downloading (…)/main/tokenizer.json: 100%|█████████████████████████████████| 1.36M/1.36M [00:00<00:00, 25.7MB/s]
Downloading (…)lve/main/config.json: 100%|█████████████████████████████████████| 665/665 [00:00<00:00, 2.43MB/s]
Attempting to retrieve the General and Moderations DB
Retrieved the General and Moderations DB
Attempting to retrieve the General and Moderations DB
Traceback (most recent call last):
  File "/home/adam/Research/machine-learning/GPTDiscord/GPTDiscord/bin/gpt3discord", line 5, in <module>
    from gpt3discord import init
  File "/home/adam/Research/machine-learning/GPTDiscord/GPTDiscord/lib/python3.10/site-packages/gpt3discord.py", line 22, in <module>
    from cogs.index_service_cog import IndexService
  File "/home/adam/Research/machine-learning/GPTDiscord/GPTDiscord/lib/python3.10/site-packages/cogs/index_service_cog.py", line 13, in <module>
    from models.index_model import Index_handler
  File "/home/adam/Research/machine-learning/GPTDiscord/GPTDiscord/lib/python3.10/site-packages/models/index_model.py", line 66, in <module>
    EpubReader = download_loader("EpubReader")
  File "/home/adam/Research/machine-learning/GPTDiscord/GPTDiscord/lib/python3.10/site-packages/llama_index/readers/download.py", line 133, in download_loader
    library = json.loads(library_raw_content)
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 4 (char 3)
```

**Comment by jphccfc** [comment]
same error here too

**Comment by tacssuki** [comment]
to work temporarily comment out these lines on index_model.py : 
`EpubReader = download_loader("EpubReader")
MarkdownReader = download_loader("MarkdownReader")
RemoteReader = download_loader("RemoteReader")
RemoteDepthReader = download_loader("RemoteDepthReader")`

However, `/index` command might not work properly. I think the dev needs to do or update something on dev dependencies but he said he doesn't have time yet(he said this on discord)

**Comment by pushpixels** [comment]
Any updates on this?

**Comment by AreYouMehmetEfeisModder** [comment]
> ###
> **[tacssuki](/tacssuki) ** commented [Jun 12, 2023](#issuecomment-1586666506) •

thats fixed version ? 
https://github.com/lsnk/GPTDiscord

**Comment by AreYouMehmetEfeisModder** [comment]
I wonder when kav will fix this

**Comment by pushpixels** [comment]
/internet chat doesn't work
An error occured while using internet connected chat: Error: 'GPTVectorStoreIndex' object has no attribute 'query'

I used this without Docker:
https://github.com/lsnk/GPTDiscord

**Comment by Hikari-Haru** [comment]
It'll be fixed in the next update

**Comment by mgunnin** [comment]
This is still an issue for me.

`2023-06-26 14:50:53 Loading environment from .env
2023-06-26 14:50:53 Loading environment from /opt/gpt3discord/etc/environment
2023-06-26 14:50:53 Loading environment from None
2023-06-26 14:50:53 Attempting to retrieve the settings DB
2023-06-26 14:50:53 Retrieved the settings DB
Downloading (…)olve/main/vocab.json: 100%|██████████| 1.04M/1.04M [00:00<00:00, 6.37MB/s]
Downloading (…)olve/main/merges.txt: 100%|██████████| 456k/456k [00:00<00:00, 4.54MB/s]
Downloading (…)/main/tokenizer.json: 100%|██████████| 1.36M/1.36M [00:00<00:00, 8.17MB/s]
Downloading (…)lve/main/config.json: 100%|██████████| 665/665 [00:00<00:00, 256kB/s]
2023-06-26 14:50:58 Traceback (most recent call last):
2023-06-26 14:50:58   File "/opt/gpt3discord/bin/gpt3discord.py", line 22, in <module>
2023-06-26 14:50:58     from cogs.index_service_cog import IndexService
2023-06-26 14:50:58   File "/usr/local/lib/python3.10/site-packages/cogs/index_service_cog.py", line 10, in <module>
2023-06-26 14:50:58     from models.index_model import Index_handler
2023-06-26 14:50:58   File "/usr/local/lib/python3.10/site-packages/models/index_model.py", line 59, in <module>
2023-06-26 14:50:58     EpubReader = download_loader("EpubReader")
2023-06-26 14:50:58   File "/usr/local/lib/python3.10/site-packages/llama_index/readers/download.py", line 133, in download_loader
2023-06-26 14:50:58 Attempting to retrieve the General and Moderations DB
2023-06-26 14:50:58 Retrieved the General and Moderations DB
2023-06-26 14:50:58 Attempting to retrieve the General and Moderations DB
2023-06-26 14:50:58     library = json.loads(library_raw_content)
2023-06-26 14:50:58   File "/usr/local/lib/python3.10/json/__init__.py", line 346, in loads
2023-06-26 14:50:58     return _default_decoder.decode(s)
2023-06-26 14:50:58   File "/usr/local/lib/python3.10/json/decoder.py", line 340, in decode
2023-06-26 14:50:58     raise JSONDecodeError("Extra data", s, end)
2023-06-26 14:50:58 json.decoder.JSONDecodeError: Extra data: line 1 column 4 (char 3)`
