### ISSUE TITLE
[BUG] Code interpreter upload file location issue

### ISSUE THREAD

**Issue by AndrewsPanda** [Kav-K/GPTDiscord#372]
Started code interpreter chat by uploading an .xlsx file and asking it to analyse the document.

1. It saved the file to a directory called, '/home/user'
2. When asking it to perform further iterations, it is saying the file is not in the right folder:

It send this message:

```
I apologize for the confusion, but it seems there was an error because the file artifacts/REMVR_AI2.xlsx could not be found.

As an AI, I don't have the ability to access or move files in your system. The code I provided assumes that the file REMVR_AI2.xlsx is located in the artifacts directory.

Please ensure that the file is located in the correct directory and try again. If the file is located in a different directory, please provide the correct path and I will adjust the code accordingly.
```

**To Reproduce**
Steps to reproduce the behaviour:
1. /code chat
3. Uploaded an .xlsx file asking the bot to analyse the file
4. Upon requesting it to perform different functions on the same file, it's saying it is in the wrong folder.

```
I apologize for the confusion, but it seems there was an error because the file `artifacts/REMVR_AI2.xlsx` could not be found. 

As an AI, I don't have the ability to access or move files in your system. The code I provided assumes that the file `REMVR_AI2.xlsx` is located in the `artifacts` directory. 

Please ensure that the file is located in the correct directory and try again. If the file is located in a different directory, please provide the correct path and I will adjust the code accordingly.


> Entering new AgentExecutor chain...

Invoking: `Code-execution-tool` with `import pandas as pd

# Load spreadsheet
xl = pd.ExcelFile('artifacts/REMVR_AI2.xlsx')

# Load a sheet into a DataFrame by its name
df = xl.parse(xl.sheet_names[0])

# Select only the columns we're interested in
df_subset = df[['DASS_Depression', 'DASS_Anxiety', 'DASS_Stress', 'Age']]

# Calculate the correlation matrix
correlation_matrix = df_subset.corr()

print(correlation_matrix)`


STDOUT: 
STDERR: Traceback (most recent call last):
  File "/tmp/main-1698799175.4108965.py", line 4, in <module>
    xl = pd.ExcelFile('artifacts/REMVR_AI2.xlsx')
  File "/usr/local/lib/python3.10/dist-packages/pandas/io/excel/_base.py", line 1563, in __init__
    ext = inspect_excel_format(
  File "/usr/local/lib/python3.10/dist-packages/pandas/io/excel/_base.py", line 1419, in inspect_excel_format
    with get_handle(
  File "/usr/local/lib/python3.10/dist-packages/pandas/io/common.py", line 872, in get_handle
    handle = open(handle, ioargs.mode)
FileNotFoundError: [Errno 2] No such file or directory: 'artifacts/REMVR_AI2.xlsx'
NO__ARTIFACTSI apologize for the confusion, but it seems there was an error because the file `artifacts/REMVR_AI2.xlsx` could not be found. 

As an AI, I don't have the ability to access or move files in your system. The code I provided assumes that the file `REMVR_AI2.xlsx` is located in the `artifacts` directory. 

Please ensure that the file is located in the correct directory and try again. If the file is located in a different directory, please provide the correct path and I will adjust the code accordingly.
```

**Comment by Kav-K** [comment]
This seems to be because the bot is told to use the `artifacts` folder when saving files, but it sometimes gets confused and uses that for when searching for files that you upload too, I'll edit the prompt to make this work a little smoother, please re-open the issue if you run into this again after 12.0.1's update.
