### ISSUE TITLE
Removing a thread from awaiting a response should be safer

### ISSUE THREAD

**Issue by cherryroots** [Kav-K/GPTDiscord#389]
When a thread's already been removed or not in it for some reason it should just silently pass.

```python
Traceback (most recent call last):
File "/home/bots/discord_bots/GPT3Discord/models/index_model.py", line 699, in index_webpage
    raise ValueError(
ValueError: Invalid URL or could not connect to the provided URL.
The summary is None
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/bots/.local/lib/python3.9/site-packages/discord/client.py", line 378, in _run_event
    await coro(*args, **kwargs)
  File "/home/bots/discord_bots/GPT3Discord/cogs/index_service_cog.py", line 168, in on_message
    self.thread_awaiting_responses.remove(message.channel.id)
ValueError: list.remove(x): x not in list

**Comment by Paillat-dev** [comment]
I will see what I can do
