### ISSUE TITLE
"Failed to start code interpreter session. This may be an issue with E2B. Please try again later." [BUG] 

### ISSUE THREAD

**Issue by pushpixels** [Kav-K/GPTDiscord#473]
Failed to acquire sandbox
Traceback (most recent call last):
  File "/root/GPTDiscord/cogs/code_interpreter_service_cog.py", line 304, in __init__
    self.session = DataAnalysis(api_key=E2B_API_KEY)
  File "/usr/local/lib/python3.9/dist-packages/e2b/templates/data_analysis.py", line 44, in __init__
    super().__init__(
  File "/usr/local/lib/python3.9/dist-packages/e2b/sandbox/main.py", line 102, in __init__
    super().__init__(
  File "/usr/local/lib/python3.9/dist-packages/e2b/sandbox/sandbox_connection.py", line 97, in __init__
    self._open(timeout=timeout)
  File "/usr/local/lib/python3.9/dist-packages/e2b/sandbox/main.py", line 121, in _open
    super()._open(timeout=timeout)
  File "/usr/local/lib/python3.9/dist-packages/e2b/sandbox/sandbox_connection.py", line 201, in _open
    raise e
  File "/usr/local/lib/python3.9/dist-packages/e2b/sandbox/sandbox_connection.py", line 170, in _open
    self._sandbox = api.instances_post(
  File "/usr/local/lib/python3.9/dist-packages/pydantic/_internal/_validate_call.py", line 100, in __call__
    res = self.__pydantic_validator__.validate_python(pydantic_core.ArgsKwargs(args, kwargs))
  File "/usr/local/lib/python3.9/dist-packages/e2b/api/v2/client/api/instances_api.py", line 218, in instances_post
    return self.instances_post_with_http_info(new_instance, **kwargs)  # noqa: E501
  File "/usr/local/lib/python3.9/dist-packages/pydantic/_internal/_validate_call.py", line 100, in __call__
    res = self.__pydantic_validator__.validate_python(pydantic_core.ArgsKwargs(args, kwargs))
  File "/usr/local/lib/python3.9/dist-packages/e2b/api/v2/client/api/instances_api.py", line 325, in instances_post_with_http_info
    return self.api_client.call_api(
  File "/usr/local/lib/python3.9/dist-packages/e2b/api/v2/client/api_client.py", line 448, in call_api
    return self.__call_api(
  File "/usr/local/lib/python3.9/dist-packages/e2b/api/v2/client/api_client.py", line 242, in __call_api
    raise e
  File "/usr/local/lib/python3.9/dist-packages/e2b/api/v2/client/api_client.py", line 229, in __call_api
    response_data = self.request(
  File "/usr/local/lib/python3.9/dist-packages/e2b/api/v2/client/api_client.py", line 526, in request
    return self.rest_client.post_request(
  File "/usr/local/lib/python3.9/dist-packages/e2b/api/v2/client/rest.py", line 352, in post_request
    return self.request(
  File "/usr/local/lib/python3.9/dist-packages/e2b/api/v2/client/rest.py", line 259, in request
    raise NotFoundException(http_resp=r)
e2b.api.v2.client.exceptions.NotFoundException: (404)
Reason: Not Found
HTTP response headers: HTTPHeaderDict({'content-type': 'application/json; charset=utf-8', 'date': 'Mon, 25 Mar 2024 08:37:24 GMT', 'Content-Length': '74', 'via': '1.1 google', 'Alt-Svc': 'h3=":443"; ma=2592000,h3-29=":443"; ma=2592000'})
HTTP response body: {"code":404,"message":"validation error: no matching operation was found"}

**Comment by pushpixels** [comment]
E2B dev "We've changed few thing a while back and it was backward incompatible, so we changed some endpoints and we removed the support on Sunday. So I think this could be the cause"
